In [0]:
import pandas as pd
import numpy as np

In [0]:
company_df = pd.read_csv("Data.csv",encoding = "ISO-8859-1")

In [5]:
company_df.head(10)

         Date  ...                                           Top25
0  2000-01-03  ...                              Recovering a title
1  2000-01-04  ...                    Millennium bug fails to bite
2  2000-01-05  ...                                    Useful links
3  2000-01-06  ...                     Lessons of law's hard heart
4  2000-01-07  ...                                      Gone aloft
5  2000-01-10  ...                Met lent stopped car to Lawrence
6  2000-01-11  ...                          Repairing Jack's house
7  2000-01-12  ...  Press reaction from Spain, Chile and Argentina
8  2000-01-13  ...     Harrods loses Prince Philip's royal warrant
9  2000-01-14  ...                                Scissors at dawn

[10 rows x 27 columns]

In [6]:
company_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101 entries, 0 to 4100
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4101 non-null   object
 1   Label   4101 non-null   int64
 2   Top1    4101 non-null   object
 3   Top2    4101 non-null   object
 4   Top3    4101 non-null   object
 5   Top4    4101 non-null   object
 6   Top5    4101 non-null   object
 7   Top6    4101 non-null   object
 8   Top7    4101 non-null   object
 9   Top8    4101 non-null   object
 10  Top9    4101 non-null   object
 11  Top10   4101 non-null   object
 12  Top11   4101 non-null   object
 13  Top12   4101 non-null   object
 14  Top13   4101 non-null   object
 15  Top14   4101 non-null   object
 16  Top15   4101 non-null   object
 17  Top16   4101 non-null   object
 18  Top17   4101 non-null   object
 19  Top18   4101 non-null   object
 20  Top19   4101 non-null   object
 21  Top20   4101 non-null   object
 22  Top21   4101 non-null   object
 23  Top22   4101 non-null   object
 24  Top23   4100 non-null   object
 25  Top24   4098 non-null   object
 26  Top25   4098 non-null   object
dtypes: int64(1), object(26)
memory usage: 865.2+ KB

In [7]:
company_df.describe(include= "all")

              Date  ...                           Top25
count         4101  ...                            4098
unique        4101  ...                            4066
top     2006-06-19  ...  Corrections and clarifications
freq             1  ...                               6
mean           NaN  ...                             NaN
std            NaN  ...                             NaN
min            NaN  ...                             NaN
25%            NaN  ...                             NaN
50%            NaN  ...                             NaN
75%            NaN  ...                             NaN
max            NaN  ...                             NaN

[11 rows x 27 columns]

In [8]:
company_df.shape

(4101, 27)

In [9]:
company_df.size

110727

In [10]:
company_df.isnull()

       Date  Label   Top1   Top2   Top3  ...  Top21  Top22  Top23  Top24  Top25
0     False  False  False  False  False  ...  False  False  False  False  False
1     False  False  False  False  False  ...  False  False  False  False  False
2     False  False  False  False  False  ...  False  False  False  False  False
3     False  False  False  False  False  ...  False  False  False  False  False
4     False  False  False  False  False  ...  False  False  False  False  False
...     ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
4096  False  False  False  False  False  ...  False  False  False  False  False
4097  False  False  False  False  False  ...  False  False  False  False  False
4098  False  False  False  False  False  ...  False  False  False  False  False
4099  False  False  False  False  False  ...  False  False  False  False  False
4100  False  False  False  False  False  ...  False  False  False  False  False

[4101 rows x 27 columns]

In [13]:
Isnull = company_df.isnull().sum()/len(company_df)*100
Isnull = Isnull[Isnull>0]
Isnull.sort_values(inplace=True, ascending=False)
Isnull

Top25    0.073153
Top24    0.073153
Top23    0.024384
dtype: float64

In [0]:
train = company_df[company_df['Date'] < '20150101']
test = company_df[company_df['Date'] > '20141231']

In [16]:
train.tail()

            Date  ...                                              Top25
3970  2015-12-24  ...  Cameron, Osborne and Murdoch back together at ...
3971  2015-12-28  ...  Experiment in Germany tests the idea of an 'em...
3972  2015-12-29  ...  Israel warns Brazil to accept its settler amba...
3973  2015-12-30  ...  UK Sperm Bank Doesn't Accept Donors with Dysle...
3974  2015-12-31  ...  Hamas to keep Palestinians from ringing in New...

[5 rows x 27 columns]

In [18]:
test.tail()

            Date  ...                                              Top25
4096  2016-06-27  ...  Pakistani clerics declare transgender marriage...
4097  2016-06-28  ...  Mexico's security forces routinely use 'sexual...
4098  2016-06-29  ...  Tiny New Zealand town with 'too many jobs' lau...
4099  2016-06-30  ...  Law Enforcement Sources: Gun Used in Paris Ter...
4100  2016-07-01  ...  Ozone layer hole seems to be healing - US &amp...

[5 rows x 27 columns]

In [23]:
# Removing punctuations
data=train.iloc[:,2:27]
data.replace("[^a-zA-Z]"," ",regex=True, inplace=True)

data.head()

                                                Top1  ...                         Top25
0  A  hindrance to operations   extracts from the...  ...            Recovering a title
1                                          Scorecard  ...  Millennium bug fails to bite
2                  Coventry caught on counter by Flo  ...                  Useful links
3                      Pilgrim knows how to progress  ...   Lessons of law s hard heart
4                               Hitches and Horlocks  ...                    Gone aloft

[5 rows x 25 columns]

In [25]:
# Renaming column names for ease of access
list1= [i for i in range(25)]
new_Index=[str(i) for i in list1]
data.columns= new_Index
data.head(5)

                                                   0  ...                            24
0  A  hindrance to operations   extracts from the...  ...            Recovering a title
1                                          Scorecard  ...  Millennium bug fails to bite
2                  Coventry caught on counter by Flo  ...                  Useful links
3                      Pilgrim knows how to progress  ...   Lessons of law s hard heart
4                               Hitches and Horlocks  ...                    Gone aloft

[5 rows x 25 columns]

In [26]:
# Convertng headlines to lower case
for index in new_Index:
    data[index]=data[index].str.lower()
data.head(1)

                                                   0  ...                  24
0  a  hindrance to operations   extracts from the...  ...  recovering a title

[1 rows x 25 columns]

In [27]:
' '.join(str(x) for x in data.iloc[1,0:25])

'scorecard the best lake scene leader  german sleaze inquiry cheerio  boyo the main recommendations has cubie killed fees  has cubie killed fees  has cubie killed fees  hopkins  furious  at foster s lack of hannibal appetite has cubie killed fees  a tale of two tails i say what i like and i like what i say elbows  eyes and nipples task force to assess risk of asteroid collision how i found myself at last on the critical list the timing of their lives dear doctor irish court halts ira man s extradition to northern ireland burundi peace initiative fades after rebels reject mandela as mediator pe points the way forward to the ecb campaigners keep up pressure on nazi war crimes suspect jane ratcliffe yet more things you wouldn t know without the movies millennium bug fails to bite'

In [0]:
headlines = []
for row in range(0,len(data.index)):
    headlines.append(' '.join(str(x) for x in data.iloc[row,0:25]))

In [29]:
headlines[0]

'a  hindrance to operations   extracts from the leaked reports scorecard hughes  instant hit buoys blues jack gets his skates on at ice cold alex chaos as maracana builds up for united depleted leicester prevail as elliott spoils everton s party hungry spurs sense rich pickings gunners so wide of an easy target derby raise a glass to strupar s debut double southgate strikes  leeds pay the penalty hammers hand robson a youthful lesson saints party like it s      wear wolves have turned into lambs stump mike catches testy gough s taunt langer escapes to hit     flintoff injury piles on woe for england hunters threaten jospin with new battle of the somme kohl s successor drawn into scandal the difference between men and women sara denver  nurse turned solicitor diana s landmine crusade put tories in a panic yeltsin s resignation caught opposition flat footed russian roulette sold out recovering a title'

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

In [0]:
## implement BAG OF WORDS
countvector=CountVectorizer(ngram_range=(2,2))
traindataset=countvector.fit_transform(headlines)

In [32]:
# implement RandomForest Classifier
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(traindataset,train['Label'])

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
## Predict for the Test Dataset
test_transform= []
for row in range(0,len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))
test_dataset = countvector.transform(test_transform)
predictions = randomclassifier.predict(test_dataset)

In [0]:

## Import library to check accuracy
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [35]:
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[142  44]
 [  8 184]]
0.8624338624338624
              precision    recall  f1-score   support

           0       0.95      0.76      0.85       186
           1       0.81      0.96      0.88       192

    accuracy                           0.86       378
   macro avg       0.88      0.86      0.86       378
weighted avg       0.88      0.86      0.86       378